### ISSUE TITLE
@interfaces should be @dhcp_interfaces in templates/redhat/systemd-dropin.conf.erb

### ISSUE THREAD

**Issue by TJM** [theforeman/puppet-dhcp#122]
With the puppet code:

```puppet
include dhcp
```

and the hieradata:

```yaml
dhcp::interface "${facts.networking.primary}"
```

The catalog compilation fails with the following error:

```
Error while evaluating a Function Call, Failed to parse template dhcp/redhat/systemd-dropin.conf.erb:
  Filepath: /etc/puppetlabs/code/environments/dhcpd/modules/dhcp/templates/redhat/systemd-dropin.conf.erb
  Line: 3
  Detail: undefined method `join' for nil:NilClass
 (file: /etc/puppetlabs/code/environments/dhcpd/modules/dhcp/manifests/init.pp, line: 88, column: 22)
```

The problem is that the template is attempting to use the parameter `@interfaces` instead of `@dhcp_interfaces` which is set https://github.com/theforeman/puppet-dhcp/blob/e5f9135c938b4a41ca29e5bd6ebfef779fb40014/manifests/init.pp#L39-L48

I would honestly recommend, while you are looking at that to just set the default interface using the fact like we did above in hieradata.

**Comment by TJM** [comment]
Simple workaround is to use interfaces array instead...

```yaml
dhcp::interfaces: [ "${facts.networking.primary}" ]
```

**Comment by ekohl** [comment]
We should really properly sort this out at some point and remove this overly complicated code, but for now I'll implement your suggestion.

**Comment by ekohl** [comment]
I opened https://github.com/theforeman/puppet-dhcp/pull/124 to do a 4.1.1 bugfix release. Thanks for the report.

**Comment by TJM** [comment]
@ekohl Thanks for the lightning fast fix! I was going to suggest that the next "major" release should maybe do away with the multiple parameters to set the same setting. Probably with some upcoming release that still "accepts" the option but sends a "notify" to let people know to update. In addition, specifying the interfaces should *not* be required, it should be optional. DHCPd should listen on all interfaces *unless* the user has some special environment  which requires them to limit it to a specific subset of the interfaces.

Thanks again,
Tommy

**Comment by ekohl** [comment]
@TJM I 100% agree with you on that for the next major release. It kind of slipped my mind on the last major release.
