### ISSUE TITLE
Add support for options in dhcp pool

### ISSUE THREAD

**Issue by lvg** [theforeman/puppet-dhcp#21]
Support for an option-array of options to be added in the dhcp-pool:

Example:
```
dhcp::pool { "name":
  ....
  options => [
    'domain-search       "pro.localdomain", "ont.localdomain"',
    'broadcast-address   192.168.0.254',
    'domain-name-servers 192.168.0.10, 192.168.0.11',
  ]
}
```

The puppetlabs/dhcp is almost the same as theforeman/puppet-dhcp and puppetlabs support this but that module isn't supported by theforeman puppet modules.

**Comment by ekohl** [comment]
This was fixed in https://github.com/theforeman/puppet-dhcp/commit/d0a2c0af2e82542cc1d324b1c5c8c135bcfbf0ce
