### ISSUE TITLE
please provide a new release

### ISSUE THREAD

**Issue by bastelfreak** [theforeman/puppet-dhcp#210]
Hi,
could you please publish a new version of the module? The 8.0.0 release on the forge doesn't allow puppetlabs/stdlib 8.1.0. The metadata.json in master already allows it. I've the same request for:
* theforeman/dns
* theforeman/puppet
* theforeman/puppetserver_foreman
* theforeman/tftp
I didn't raise separate issues for them. Please let me know if I should do that.

**Comment by ekohl** [comment]
I wanted to do that last week, but haven't gotten around to it yet. It's needed since we're getting to the point in the Foreman release cycle where it's needed. No separate issues are needed.

**Comment by ekohl** [comment]
I forgot to close this when I released 8.1.0
