### ISSUE TITLE
Failed to convert '/var/lib/puppet/concat/output/["dhcp.conf"].out' to URI

### ISSUE THREAD

**Issue by tisoft** [theforeman/puppet-dhcp#25]
I get the following error with the dhcp module:

Error: Failed to apply catalog: Parameter source failed on File[/etc/dhcp/dhcpd.conf]: Failed to convert '/var/lib/puppet/concat/output/["dhcp.conf"].out' to URI: bad component(expected absolute path component): /var/lib/puppet/concat/output/[%22dhcp.conf%22].out at /var/lib/puppet/environments/production/modules/dhcp/manifests/init.pp:83
Wrapped exception:
Failed to convert '/var/lib/puppet/concat/output/["dhcp.conf"].out' to URI: bad component(expected absolute path component): /var/lib/puppet/concat/output/[%22dhcp.conf%22].out

Any hints what I can do to fix it?

**Comment by mmoll** [comment]
@tisoft any update on this?

**Comment by tisoft** [comment]
It is working now but I don't know what fixed it.

**Comment by mmoll** [comment]
thanks :+1:
