### ISSUE TITLE
Issue disabling the pool

### ISSUE THREAD

**Issue by overholw** [theforeman/puppet-dhcp#29]
Our foreman deployment model is to put a dhcp/tftp server on each subnet.    Now we are being requested to deploy to subnets where we can not control the IPs with dhcp.   

My thought is to build a dhcp/tftp server that only serves static reservations.    The <% if @range -%> in  templates/dhcpd.pool.erb the check is always returning true because foreman is passing the value as a string, so not disabling the pool definition.   

 My quick hack was to change the line to:
   <% if (@range and (@range =~ /\d/)) -%>

This was sufficient for my testing, but is probably not ideal to be published.    Better suggestions are welcome.

**Comment by ekohl** [comment]
I've been able to reproduce this. I was sending the boolean value false and not an empty string. Setting it simply to an empty string is insufficient.
