### ISSUE TITLE
dhcp domain-search

### ISSUE THREAD

**Issue by lbischof** [theforeman/puppet-dhcp#70]
It seems the syntax for the domain-search option is wrong. Current syntax:
```
option domain-search "domain.com, domain.org";
```
That didn't work for me and I tried:
```
option domain-search "domain.com", "domain.org";
```
and it worked! I'm not exactly sure if this is a version conflict because I can't find any documentation in the man pages of dhcpd.conf.

**Comment by domcleal** [comment]
Yes, it looks more like a bug in the template.

**Comment by ekohl** [comment]
This was introduced in https://github.com/theforeman/puppet-dhcp/commit/1ad54b36f7dbb2876aa84ec28d63401de4c7e863 so I wonder if anyone actually tested it with multiple search domains.
