### ISSUE TITLE
Pool Description

### ISSUE THREAD

**Issue by mat1010** [theforeman/puppet-dhcp#74]
Hello,
is there a specific reason for defining the pool description within `templates/dhcpd.pool.erb` like this?
```
#################################
# <%= @name %>
#################################
```
Some tools like [Webmin](http://www.webmin.com/) rely on the first comment to name the pools within the webinterface. In the above mentioned case it will be displayed as `#################################` which is kind of useless.

Would you mind if we adjust this to the following?
```
# <%= @name %>
```
- mat1010

**Comment by mat1010** [comment]
@mmoll Thanks for the reply - I will create a PR for this.

> Tool like webmin togetehr with Puppet feels strange, I guess you're using it only to view pool information in the WebUI?
You're totally right - this is a system provided to one of our customers. He wants to be able to clear leases and view the pool config without having to login to the shell. Therefore we configured the whole system using puppet and give him the possibility to use webmin to clear the leases.

He's also aware that all config changes through the UI will be reverted.

**Comment by ekohl** [comment]
Would https://github.com/theforeman/foreman_dhcp_browser be an interesting plugin for that?

**Comment by mat1010** [comment]
@ekhol Thanks for your reply. We are already using the mentioned plugin for our foreman setup. But in the above mentioned setup the DHCP server is used for clients only and is not connected the our foreman.

**Comment by ekohl** [comment]
Cool
