### ISSUE TITLE
Compatible with Puppet 4?

### ISSUE THREAD

**Issue by HyperBaton** [theforeman/puppet-dhcp#76]
The changelog for version 2.0.0 states the following:

> Test with future parser and Puppet 4

However, the Puppet Forge compatibility states this:

> Puppet Enterprise 3.8.x, 3.7.x, 3.3.x, 3.2.x, 3.1.x
> Puppet >= 3.0.0 < 4.0.0

This leaves me a bit confused...

**Comment by domcleal** [comment]
4.x is indeed supported, we just forgot to update the metadata.  This has been fixed in 2.3.2, uploaded to the Forge.

**Comment by HyperBaton** [comment]
Cool, cheers. Thanks for the confirmation.
