### ISSUE TITLE
Allow multiple pools per subnet

### ISSUE THREAD

**Issue by geof77** [theforeman/puppet-dhcp#80]
Hello,

I have modified the dhcp module to allow multiple pools per subnet and I'd like to propose it for inclusion in your module.

I'd be glad if you could have a look at the fork geof77/puppet-dhcp and give me feedback on the modifications.  The README has also been modified to reflect the improvements and give usage examples. 

I hope you find this useful, at least it is very useful for me :-)

Use case:

I want to change the pxefilename for clients matching a filter, e.g. the hostname (dhcp::host definition) begins with "ppc".

1) create dhcp::host definitions
2) create "ppc64" dhcp::class, match if hostname begins with 'ppc'
3) create subnet with common attributes (network, mask, gateway, pxeserver,...)
4) create two pools with different ranges within this subnet (previously not possible)
5) through the "(pool_)parameters" attribute, pass 
    'allow members of "ppc64"' and 'filename "ppcxyz"' to the first pool
    'deny members of "ppc64"' to the second pool

Implementation:

Note: I did not care about backward compatibility yet.

Split dhcp::pool in two:
- A 'dhcp::subnet' definition containing only network-related attributes
- A 'dhcp::subnet::pool' definition containing the range (and pxefilename overrides)
  Split templates in two:
- A 'dhcpd.subnet.erb' template
- A 'dhcpd.pool.erb' template
  Replace pool.pp manifest with subnet.pp containing "dhcp::subnet" and "dhcp::subnet::pool"
  Modify init.pp to create subnet  and pool resources.

Other improvements in my fork:
- Allow pxefilename and pxeserver overrides in the subnet and/or pool instances
- Add allow_class and deny_class parameters to the pools to avoid using plain text "parameters" (i.e. "allow members of ...")

Best regards,
Geof

**Comment by ekohl** [comment]
It would be easier if you could submit this as a pull request.

Some notes initial notes:
* I'd prefer to maintain dhcp::pool (even if with a deprecation notice) so we don't break existing deployments.
* Tests would help a lot. Especially where you pass in parameters and verify the generated config because there are quite a few conditionals.

**Comment by ekohl** [comment]
@geof77 what's the status? Anything we can do to move this in the right direction?

**Comment by elisiano** [comment]
This would be useful to me too (for different reasons)!
@geof77: any chance for you to submit that PR?

**Comment by geof77** [comment]
Hi, maybe but it's been a while since I had a chance work on this.  I need
to have a look at it.


Cordialement,

-- 
Geoffroy Stévenne

2017-05-20 21:36 GMT+02:00 Elisiano Petrini <notifications@github.com>:
